# wrangler.toml
# Place this in the root of your odesandcodes repo

name = "odesandcodes"
compatibility_date = "2024-01-01"

[assets]
directory = "./dist"

[[kv_namespaces]]
binding = "SESSIONS"
id = "44efcb1959944c1097a5b5df3e2e0d33"